server:
  port: 8082

spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/portfolio_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: "86400000"

user-service:
  url: http://localhost:8081